import type { Property } from '@/lib/types/domain'

/* Base simulada de imoveis (PRD 21, Marco 1: "seed de 50-150 imoveis simulados").
   Este arquivo e a fonte unica: alimenta a UI enquanto o Supabase nao existe e
   vira o INSERT do seed SQL depois. As combinacoes cobrem de proposito os
   cenarios 1 e 2 do hackathon — apartamento na zona sul para compra (Exemplo 1)
   e unidades compactas com perfil de renda para investimento (Exemplo 2).

   Hoje sao 24 imoveis; ampliar ate a faixa do PRD antes da demonstracao. */

/** Evita erro de escala: o schema guarda centavos, o catalogo se le em reais. */
const reais = (v: number) => Math.round(v * 100)

/* Sem `id`: o UUID e gerado pelo banco no insert. Inventar id aqui so criaria um
   identificador que nao corresponde a nada depois do seed rodar.
   A chave natural do catalogo e reference_code, que tem UNIQUE no schema. */
type SeedProperty = Omit<Property, 'id' | 'owner_registration_id' | 'broker_id'>

export const SEED_PROPERTIES: SeedProperty[] = [
  {
    reference_code: 'LH-1001',
    title: 'Apartamento reformado a duas quadras do metro Ana Rosa',
    operation: 'venda',
    property_type: 'apartamento',
    price_cents: reais(820_000),
    rent_price_cents: null,
    condo_fee_cents: reais(680),
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parking_spots: 1,
    area_m2: 68,
    region: 'Vila Mariana',
    city: 'São Paulo',
    address: 'Rua Domingos de Morais, 1200',
    description:
      'Reformado em 2024, andar alto, sol da manha. Dois quartos com armarios embutidos, sendo uma suite. Predio com portaria 24h. A 400m da estacao Ana Rosa.',
    amenities: ['portaria 24h', 'elevador', 'area de servico', 'perto do metro'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-05-12T10:00:00Z',
  },
  {
    reference_code: 'LH-1002',
    title: 'Cobertura duplex com terraco em Moema',
    operation: 'venda',
    property_type: 'cobertura',
    price_cents: reais(2_450_000),
    rent_price_cents: null,
    condo_fee_cents: reais(2_100),
    bedrooms: 3,
    suites: 2,
    bathrooms: 4,
    parking_spots: 3,
    area_m2: 210,
    region: 'Moema',
    city: 'São Paulo',
    address: 'Alameda dos Nhambiquaras, 800',
    description:
      'Duplex com terraco de 60m2, churrasqueira e vista livre para o Parque Ibirapuera. Tres dormitorios, duas suites, lavabo social.',
    amenities: ['terraco', 'churrasqueira', 'vista livre', 'piscina', 'academia'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-04-28T10:00:00Z',
  },
  {
    reference_code: 'LH-1003',
    title: 'Studio compacto mobiliado no Itaim Bibi',
    operation: 'ambos',
    property_type: 'studio',
    price_cents: reais(590_000),
    rent_price_cents: reais(3_400),
    condo_fee_cents: reais(720),
    bedrooms: 1,
    suites: 0,
    bathrooms: 1,
    parking_spots: 0,
    area_m2: 32,
    region: 'Itaim Bibi',
    city: 'São Paulo',
    address: 'Rua Joaquim Floriano, 400',
    description:
      'Studio mobiliado, alta demanda de locacao por executivos. Predio com coworking e lavanderia compartilhada. Historico de ocupacao acima de 90%.',
    amenities: ['mobiliado', 'coworking', 'lavanderia', 'pet friendly'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-06-02T10:00:00Z',
  },
  {
    reference_code: 'LH-1004',
    title: 'Apartamento amplo no Campo Belo com varanda gourmet',
    operation: 'venda',
    property_type: 'apartamento',
    price_cents: reais(1_180_000),
    rent_price_cents: null,
    condo_fee_cents: reais(1_150),
    bedrooms: 3,
    suites: 1,
    bathrooms: 3,
    parking_spots: 2,
    area_m2: 118,
    region: 'Campo Belo',
    city: 'São Paulo',
    address: 'Rua Barao do Triunfo, 500',
    description:
      'Tres dormitorios, varanda gourmet integrada a sala, andar intermediario. Condominio com quadra e salao de festas.',
    amenities: ['varanda gourmet', 'quadra', 'salao de festas', 'playground'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-03-19T10:00:00Z',
  },
  {
    reference_code: 'LH-1005',
    title: 'Apartamento para locacao em Pinheiros',
    operation: 'aluguel',
    price_cents: null,
    property_type: 'apartamento',
    rent_price_cents: reais(4_800),
    condo_fee_cents: reais(890),
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parking_spots: 1,
    area_m2: 74,
    region: 'Pinheiros',
    city: 'São Paulo',
    address: 'Rua dos Pinheiros, 900',
    description:
      'Dois dormitorios com suite, cozinha americana. A 600m da estacao Faria Lima. Aceita pet de pequeno porte.',
    amenities: ['pet friendly', 'perto do metro', 'cozinha americana'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-06-21T10:00:00Z',
  },
  {
    reference_code: 'LH-1006',
    title: 'Casa terrea com quintal na Saude',
    operation: 'venda',
    property_type: 'casa',
    price_cents: reais(1_050_000),
    rent_price_cents: null,
    condo_fee_cents: null,
    bedrooms: 3,
    suites: 1,
    bathrooms: 2,
    parking_spots: 2,
    area_m2: 160,
    region: 'Saúde',
    city: 'São Paulo',
    address: 'Rua Vergueiro, 4200',
    description:
      'Casa terrea em rua tranquila, quintal com area gourmet, tres dormitorios. Sem condominio. Proxima ao metro Praca da Arvore.',
    amenities: ['quintal', 'area gourmet', 'sem condominio'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-02-08T10:00:00Z',
  },
  {
    reference_code: 'LH-1007',
    title: 'Studio novo na Vila Madalena, alto potencial de renda',
    operation: 'ambos',
    property_type: 'studio',
    price_cents: reais(520_000),
    rent_price_cents: reais(3_100),
    condo_fee_cents: reais(640),
    bedrooms: 1,
    suites: 0,
    bathrooms: 1,
    parking_spots: 0,
    area_m2: 28,
    region: 'Vila Madalena',
    city: 'São Paulo',
    address: 'Rua Harmonia, 300',
    description:
      'Entrega em 2025, nunca locado. Regiao com forte demanda de locacao de curta e media temporada.',
    amenities: ['novo', 'rooftop', 'bicicletario'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-06-30T10:00:00Z',
  },
  {
    reference_code: 'LH-1008',
    title: 'Apartamento com vista para o parque no Brooklin',
    operation: 'venda',
    property_type: 'apartamento',
    price_cents: reais(1_690_000),
    rent_price_cents: null,
    condo_fee_cents: reais(1_480),
    bedrooms: 3,
    suites: 2,
    bathrooms: 3,
    parking_spots: 2,
    area_m2: 142,
    region: 'Brooklin',
    city: 'São Paulo',
    address: 'Rua Michigan, 200',
    description:
      'Andar alto com vista permanente para o parque. Tres dormitorios, duas suites, dependencia completa.',
    amenities: ['vista para o parque', 'dependencia', 'piscina', 'academia'],
    photos: [],
    status: 'reservado',
    created_at: '2026-01-24T10:00:00Z',
  },
  {
    reference_code: 'LH-1009',
    title: 'Apartamento de dois dormitorios em Perdizes',
    operation: 'venda',
    property_type: 'apartamento',
    price_cents: reais(890_000),
    rent_price_cents: null,
    condo_fee_cents: reais(920),
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parking_spots: 1,
    area_m2: 82,
    region: 'Perdizes',
    city: 'São Paulo',
    address: 'Rua Cardoso de Almeida, 1100',
    description:
      'Predio de 2018, lazer completo, proximo a PUC. Dois dormitorios amplos com suite.',
    amenities: ['lazer completo', 'academia', 'salao de festas'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-05-05T10:00:00Z',
  },
  {
    reference_code: 'LH-1010',
    title: 'Kitnet reformada perto da Paulista',
    operation: 'aluguel',
    price_cents: null,
    property_type: 'kitnet',
    rent_price_cents: reais(2_300),
    condo_fee_cents: reais(480),
    bedrooms: 1,
    suites: 0,
    bathrooms: 1,
    parking_spots: 0,
    area_m2: 26,
    region: 'Bela Vista',
    city: 'São Paulo',
    address: 'Rua Frei Caneca, 600',
    description:
      'Kitnet reformada, ideal para estudante ou primeiro imovel. A 500m da Avenida Paulista.',
    amenities: ['reformado', 'perto do metro'],
    photos: [],
    status: 'alugado',
    created_at: '2025-11-15T10:00:00Z',
  },
  {
    reference_code: 'LH-1011',
    title: 'Apartamento garden com jardim privativo no Morumbi',
    operation: 'venda',
    property_type: 'apartamento',
    price_cents: reais(1_320_000),
    rent_price_cents: null,
    condo_fee_cents: reais(1_620),
    bedrooms: 3,
    suites: 1,
    bathrooms: 3,
    parking_spots: 2,
    area_m2: 155,
    region: 'Morumbi',
    city: 'São Paulo',
    address: 'Avenida Giovanni Gronchi, 3000',
    description:
      'Garden com 40m2 de jardim privativo, condominio clube com quadra, piscina aquecida e sauna.',
    amenities: ['jardim privativo', 'piscina aquecida', 'sauna', 'quadra'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-04-11T10:00:00Z',
  },
  {
    reference_code: 'LH-1012',
    title: 'Sala comercial na Faria Lima',
    operation: 'aluguel',
    price_cents: null,
    property_type: 'comercial',
    rent_price_cents: reais(9_500),
    condo_fee_cents: reais(2_800),
    bedrooms: null,
    suites: null,
    bathrooms: 2,
    parking_spots: 2,
    area_m2: 120,
    region: 'Itaim Bibi',
    city: 'São Paulo',
    address: 'Avenida Brigadeiro Faria Lima, 3500',
    description:
      'Sala comercial em laje corporativa, ar condicionado central, piso elevado. Duas vagas.',
    amenities: ['laje corporativa', 'ar central', 'piso elevado'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-03-02T10:00:00Z',
  },
  {
    reference_code: 'LH-1013',
    title: 'Apartamento compacto em Santana com uma vaga',
    operation: 'venda',
    property_type: 'apartamento',
    price_cents: reais(465_000),
    rent_price_cents: null,
    condo_fee_cents: reais(560),
    bedrooms: 2,
    suites: 0,
    bathrooms: 1,
    parking_spots: 1,
    area_m2: 58,
    region: 'Santana',
    city: 'São Paulo',
    address: 'Rua Voluntarios da Patria, 2200',
    description:
      'Dois dormitorios, uma vaga coberta, a 300m da estacao Santana. Bom custo por metro quadrado da regiao.',
    amenities: ['perto do metro', 'vaga coberta'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-05-27T10:00:00Z',
  },
  {
    reference_code: 'LH-1014',
    title: 'Sobrado em condominio fechado no Tatuape',
    operation: 'venda',
    property_type: 'sobrado',
    price_cents: reais(980_000),
    rent_price_cents: null,
    condo_fee_cents: reais(750),
    bedrooms: 3,
    suites: 1,
    bathrooms: 3,
    parking_spots: 2,
    area_m2: 148,
    region: 'Tatuapé',
    city: 'São Paulo',
    address: 'Rua Tuiuti, 1500',
    description:
      'Sobrado em condominio fechado com seguranca 24h, tres dormitorios e quintal nos fundos.',
    amenities: ['condominio fechado', 'seguranca 24h', 'quintal'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-02-26T10:00:00Z',
  },
  {
    reference_code: 'LH-1015',
    title: 'Studio para investidor no Paraiso, ja locado',
    operation: 'venda',
    property_type: 'studio',
    price_cents: reais(610_000),
    rent_price_cents: reais(3_600),
    condo_fee_cents: reais(690),
    bedrooms: 1,
    suites: 0,
    bathrooms: 1,
    parking_spots: 0,
    area_m2: 34,
    region: 'Paraíso',
    city: 'São Paulo',
    address: 'Rua Vergueiro, 900',
    description:
      'Vendido com inquilino em contrato vigente ate 2027 — renda desde o primeiro mes. Otimo para carteira de locacao.',
    amenities: ['locado', 'perto do metro', 'mobiliado'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-06-14T10:00:00Z',
  },
  {
    reference_code: 'LH-1016',
    title: 'Apartamento alto padrao nos Jardins',
    operation: 'venda',
    property_type: 'apartamento',
    price_cents: reais(3_800_000),
    rent_price_cents: null,
    condo_fee_cents: reais(3_400),
    bedrooms: 4,
    suites: 3,
    bathrooms: 5,
    parking_spots: 4,
    area_m2: 280,
    region: 'Jardins',
    city: 'São Paulo',
    address: 'Alameda Lorena, 1200',
    description:
      'Quatro dormitorios, tres suites, sala em tres ambientes, dependencia completa. Predio classico com portaria 24h.',
    amenities: ['alto padrao', 'dependencia', 'portaria 24h', 'adega'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-01-09T10:00:00Z',
  },
  {
    reference_code: 'LH-1017',
    title: 'Apartamento de um dormitorio em Higienopolis',
    operation: 'aluguel',
    price_cents: null,
    property_type: 'apartamento',
    rent_price_cents: reais(3_900),
    condo_fee_cents: reais(1_100),
    bedrooms: 1,
    suites: 0,
    bathrooms: 1,
    parking_spots: 1,
    area_m2: 55,
    region: 'Higienópolis',
    city: 'São Paulo',
    address: 'Rua Maranhao, 400',
    description:
      'Um dormitorio amplo em predio tradicional, pe direito alto, uma vaga. Aceita pet.',
    amenities: ['pe direito alto', 'pet friendly', 'portaria 24h'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-06-08T10:00:00Z',
  },
  {
    reference_code: 'LH-1018',
    title: 'Apartamento de dois dormitorios no Butanta',
    operation: 'venda',
    property_type: 'apartamento',
    price_cents: reais(520_000),
    rent_price_cents: null,
    condo_fee_cents: reais(610),
    bedrooms: 2,
    suites: 0,
    bathrooms: 1,
    parking_spots: 1,
    area_m2: 62,
    region: 'Butantã',
    city: 'São Paulo',
    address: 'Rua Alvarenga, 1800',
    description:
      'Dois dormitorios proximo a USP e a estacao Butanta. Bom para investidor que aluga para estudante.',
    amenities: ['perto do metro', 'perto da USP'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-05-19T10:00:00Z',
  },
  {
    reference_code: 'LH-1019',
    title: 'Cobertura sem condominio no Ipiranga',
    operation: 'venda',
    property_type: 'cobertura',
    price_cents: reais(760_000),
    rent_price_cents: null,
    condo_fee_cents: reais(430),
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parking_spots: 1,
    area_m2: 96,
    region: 'Ipiranga',
    city: 'São Paulo',
    address: 'Rua Silva Bueno, 2100',
    description: 'Cobertura com terraco descoberto, condominio baixo, predio de apenas 8 unidades.',
    amenities: ['terraco', 'condominio baixo'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-04-02T10:00:00Z',
  },
  {
    reference_code: 'LH-1020',
    title: 'Apartamento para locacao na Vila Mariana',
    operation: 'aluguel',
    price_cents: null,
    property_type: 'apartamento',
    rent_price_cents: reais(3_200),
    condo_fee_cents: reais(700),
    bedrooms: 2,
    suites: 0,
    bathrooms: 1,
    parking_spots: 1,
    area_m2: 64,
    region: 'Vila Mariana',
    city: 'São Paulo',
    address: 'Rua Joaquim Tavora, 800',
    description: 'Dois dormitorios com armarios, uma vaga, a 700m do metro Vila Mariana.',
    amenities: ['armarios', 'perto do metro'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-06-25T10:00:00Z',
  },
  {
    reference_code: 'LH-1021',
    title: 'Terreno em Interlagos',
    operation: 'venda',
    property_type: 'terreno',
    price_cents: reais(420_000),
    rent_price_cents: null,
    condo_fee_cents: null,
    bedrooms: null,
    suites: null,
    bathrooms: null,
    parking_spots: null,
    area_m2: 250,
    region: 'Interlagos',
    city: 'São Paulo',
    address: 'Rua Vitorino de Morais, 90',
    description: 'Terreno plano de 10x25, zoneamento residencial, documentacao regular.',
    amenities: ['plano', 'documentacao regular'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-03-30T10:00:00Z',
  },
  {
    reference_code: 'LH-1022',
    title: 'Apartamento na Aclimacao com vista para o parque',
    operation: 'venda',
    property_type: 'apartamento',
    price_cents: reais(725_000),
    rent_price_cents: null,
    condo_fee_cents: reais(840),
    bedrooms: 2,
    suites: 1,
    bathrooms: 2,
    parking_spots: 1,
    area_m2: 71,
    region: 'Aclimação',
    city: 'São Paulo',
    address: 'Rua Muniz de Souza, 500',
    description: 'Dois dormitorios com suite, sacada com vista para o Parque da Aclimacao.',
    amenities: ['vista para o parque', 'sacada'],
    photos: [],
    status: 'disponivel',
    created_at: '2026-05-31T10:00:00Z',
  },
  /* Os dois abaixo entraram por proprietario via WhatsApp (Exemplo 4) e ainda
     nao foram aprovados — alimentam a fila de aprovacao do painel. */
  {
    reference_code: 'LH-1023',
    title: 'Apartamento de dois dormitorios no Cambuci',
    operation: 'aluguel',
    price_cents: null,
    property_type: 'apartamento',
    rent_price_cents: reais(2_600),
    condo_fee_cents: reais(520),
    bedrooms: 2,
    suites: 0,
    bathrooms: 1,
    parking_spots: 1,
    area_m2: 60,
    region: 'Cambuci',
    city: 'São Paulo',
    address: 'Rua Lavapes, 300',
    description: 'Cadastrado pelo proprietario via WhatsApp. Aguardando revisao das fotos.',
    amenities: [],
    photos: [],
    status: 'em_analise',
    created_at: '2026-08-11T10:00:00Z',
  },
  {
    reference_code: 'LH-1024',
    title: 'Casa com edicula na Penha',
    operation: 'aluguel',
    price_cents: null,
    property_type: 'casa',
    rent_price_cents: reais(2_900),
    condo_fee_cents: null,
    bedrooms: 3,
    suites: 0,
    bathrooms: 2,
    parking_spots: 2,
    area_m2: 130,
    region: 'Penha',
    city: 'São Paulo',
    address: 'Rua Doutor Joao Ribeiro, 700',
    description: 'Cadastrada pelo proprietario. Falta comprovar a metragem da edicula.',
    amenities: ['edicula', 'quintal'],
    photos: [],
    status: 'em_analise',
    created_at: '2026-08-13T10:00:00Z',
  },
]

/** Regioes distintas presentes no seed — alimenta filtros da vitrine e do painel. */
export const SEED_REGIONS = Array.from(new Set(SEED_PROPERTIES.map((p) => p.region))).sort(
  (a, b) => a.localeCompare(b, 'pt-BR')
)

/** Tipos distintos presentes no seed. */
export const SEED_PROPERTY_TYPES = Array.from(
  new Set(SEED_PROPERTIES.map((p) => p.property_type))
).sort((a, b) => a.localeCompare(b, 'pt-BR'))
